### ISSUE TITLE
can I pass AR model to vue_component?

### ISSUE THREAD

**Issue by navjeetc** [ytbryan/vuejs#12]
When calling vue_component in my erb, can I pass it a AR model instance: e.g.
```
  <%= vue_component 'project', project: @project %>
```
I tried but it did not work as to_json is called on @project and since it is unescaped, that markeup generated does not have all data . This works
```
  <% vue_component 'project, {name: @project.name, status: @project.status } %>
```
but I need to make erb call (in project.vue) for both name and status and also how do I handle associations, e.g. project has many employees and each employee has a first_name and last_name. Do I need to have a component for employee and call  vue_component for each employee in a loop ans pass employee component?

**Comment by navjeetc** [comment]
Figured this out. The main issue was that I was using an older version of Vuejs gem (beta7) and _vue_component_ helper implementation had a bug(was using double quotes v/s single quotes for values) which was causing ```@project.to_json``` to be cut off in erb and hence full json was coming into Vue component when ```erb(compName)``` was used in the component to extract JSON. The latest version (beta9) does not have this issue.

**Comment by ytbryan** [comment]
Been busy with pushing out the next version of Vue on Rails. I'm glad you figured it out yourself. 

If you prefer not to use asset pipeline. there's a webpack version of vueonrails ~> yarn add vueonrails
