### ISSUE TITLE
vuejs integration with rails/webpacker

### ISSUE THREAD

**Issue by m5o** [ytbryan/vuejs#2]
Hey Bryan 👋  

the rails core team is currently in preparation for Rails v5.1 with support for [yarn](https://github.com/rails/rails/pull/27300) and [webpack](https://github.com/rails/rails/pull/27288) lately. 

It seams you're experienced with Vue.js and integrations with rails apps in general. With all your knowledge, do you think it's possible to also promote Vue.js within webpacker task, like DHH did with [this presets tasks to use react.js](https://github.com/rails/webpacker/commit/5bb4d818af2cd825b035c51ef7bc21ee75ba4635).

I guess this would be make a lot of buzz and would be a great way to promote Vue.js 💪 with the next Rails update.

**Comment by m5o** [comment]
🔔 //cc @kimyu92

**Comment by ytbryan** [comment]
Hey @m5o 👋,  thanks for letting me know on this

I will send a PR if rails core approves it. https://github.com/rails/webpacker/issues/20

Are you guys from Malaysia? Have we met?
