### ISSUE TITLE
How run VUE js on "Production mode"?

### ISSUE THREAD

**Issue by netmask** [ytbryan/vuejs#4]
Im running my application on Heroku and the environment is "Production" but im getting this warning 
```
application-56fe55e….js:5 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```

**Comment by ytbryan** [comment]
http://stackoverflow.com/questions/41743926/disable-development-mode-warning-in-vuejs

I might include the minified version of vue in a few days time. Hopefully, it will resolve the issue. If you can, please send a PR.

**Comment by ytbryan** [comment]
Use latest gem `vuejs` #1.0.37 and use `//= require vue2.min` should fix it.

Let me know if it don't
