### ISSUE TITLE
个别标签<dd>为什么不显示？

### ISSUE THREAD

**Issue by guanfj** [ytbryan/vuejs#7]
window.onload = function() {
				new Vue({
					el: "#app",
					template: "<div>{{message}}<br><dd/></div>",
					data: {
						message: "adfadf"
					},
					components: {
						"dd": {
							template: "<h1>{{message}}</h1>",
							data: function() {
								return {
									message: "hello world"
								}
							}
						}
					}
				})
			}
其中的dd标签变量，在执行后，不会显示。
如果是程序设计里面有关键字的话，是否还有其它的标签也会这样不显示？

**Comment by ytbryan** [comment]
可以呀 https://jsfiddle.net/4wj7ahys/1/
